#!/usr/bin/env bash

usage () {
    echo "usage: $(basename $0) [--debug]"
    exit 2
}

debug_option=

if [ "$1" == "--debug" ]
then
    debug_option="--log-level debug"
elif [ -n "$1" ]
then
    echo "Unsupported option ($1)"
    usage
fi

bundle exec jekyll build
bundle exec htmlproofer ${debug_option} --check-html --allow-hash-href --http_status_ignore "401" ./_site
status=$?
if [ ${status} -ne 0 -a -z "${debug_option}" ]
then
    echo ""
    echo "htmlproofer failed to validate site contents: use --debug for more information"
fi

exit ${status}
